### ISSUE TITLE
How do you compile the example?

### ISSUE THREAD

**Issue by publicENEMY** [McNopper/OpenGL#11]
Is there a step by step noob guide on compiling the example?

**Comment by McNopper** [comment]
Did you have a look at the README? Where did you get stuck?

Meanwhile, install MingW on WIndows and Eclipse on any OS.

Norbert

**Comment by publicENEMY** [comment]
Actually, what i meant to say is, how can i compile it using visual studio 2013? or do i have to use eclipse only? i did use cmake to compile but it seems that it only compile glus, not the example. can i use cmake to compile the example?

Another thing, isnt glus is part of official OpenGL SDK? I use to see glus in opengl sdk site, but not anymore. Or did i miss something?

By the way, i find glus is a worthy alternative of glut. It simple, make code more clean, without hiding important stuff. Maybe thats why its part of OpenGL sdk.

What i wrote is what happen when i dont have enough sleep and quickly ask question before going to sleep. So dont mind me.

**Comment by publicENEMY** [comment]
Here are from the readme of glus.

How to build GLUS and the examples:

1. Install Eclipse IDE for C/C++ Developers and a GNU Compiler Collection for your operating system.
   For building with Visual C++ 2013, CMake and the Windows SDK 8.1 are needed. 

  > i have download eclipse ide for c++ (not an installer, seems portable). I have installed mingw and opted to install gnu c++ compiler. i have vs2013, cmake and win sdk 8.1. i have succesfully use cmake to make vs2013 solution and compile the solution. unfortunately, it doesnt compile any of the example.

2. Import GLUS as an existing project.

  > i assume this is for eclipse. how do i actually 'import glus as an existing project'? Opened eclipse, file->import. chose general->existing projects into workspace. in the import project dialog, select root directory, i chose \OpenGL\GLUS. i left everything as default. clicked finished.

3. Set the build configuration in Eclipse to your operating system.

  > right click in glus(under project explorer) and chose build configuration-> set active -> 20 x86 windows mingw debug. 

4. Build GLUS.

  > right clicked glus and select build project.
  > here are the errors i get.
  ```
Description	Resource	Path	Location	Type
fatal error: GL/glew.h: No such file or directory	glus.h	/GLUS/src/GL	line 53	C/C++ Problem
make: *** [src/glus_axisalignedbox.o] Error 1	GLUS		 	C/C++ Problem
Program "g++" not found in PATH			Preferences, C++/Build/Settings/Discovery, [CDT GCC Built-in Compiler Settings] options	C/C++ Scanner Discovery Problem
Program "gcc" not found in PATH			Preferences, C++/Build/Settings/Discovery, [CDT GCC Built-in Compiler Settings] options	C/C++ Scanner Discovery Problem
  ```

  > it would seems that 
  > 1. i dont have glew but glew is located at OpenGL\External\x86\Windows\MinGW\include\GL
  > 2. gcc and g++ are missing. but ive already install mingw.

5. Import an example as an existing project.
6. Set the build configuration of the example in Eclipse to your operating system.
7. Build the example.
8. The executable is located in the Binaries or VG_Binaries folder.


> Any help would be appreciated. Also, it would be nice if i can compile using vs2013.

> thanks.

**Comment by McNopper** [comment]
Regarding 1:
For GLUS, there is a CMake file, as for the Graphics Engine and OpenGL ES 2.0 examples, there are also CMake files. So for each project, there is a CMake file. If it is not in the project folder, you can not build it with CMake.

Unfortunately, there are no CMake files for the OpenGL, OpenGL ES 3.x and OpenVG examples.
Under Windows - for the OpenGL examples - you need to use Eclipse C++ with MinGW.

**Comment by McNopper** [comment]
Regarding 2:
When importing, if you are browsing with Eclipse to the "root" folder of GLUS, Example01 etc., you should see all projects etc. in the "Projects:" list of the importer dialog. To keep it easy, select and import all projects. You have to import the projects GLUS, External and Binaries. Otherwise you cannot build, as the resources are not located.

**Comment by McNopper** [comment]
Regarding 4:
You need to set the path to your MinGW and MSYS installation. Otherwise Eclispe does not find the compiler etc.

If External is not imported as a project, you cannot build, as the project files uses workspace pathes. Also, after build, the executable is copied to the Binaries folder. Same here.

**Comment by McNopper** [comment]
If I find time, I will integrate what I just wrote you into the README.
If I find more time, I will create the CMake files for the OpenGL examples :-)

Cheers Norbert

**Comment by McNopper** [comment]
Wow, yes, they have uploaded an old version of the website. I assume, this "kicked" out GLUS from the site.
I already raised a ticket to add it again.

Thanks a lot, Norbert.

**Comment by McNopper** [comment]
GLUS It is back online on the official OpenGL SDK website.

**Comment by publicENEMY** [comment]
Your instruction number 2 mention 

> 2. Import GLUS as an existing project.

yet i have to import glus, external, and binaries folder. Please update the instruction. Also, please try your instruction before you publish. 

I have fixed 'g++ not found' by resetting something in eclipse(its an eclipse issue). Glus are now able to compile. no problem there. i have also imported all example projects into the workspace. unfortunately im unable to compile the example. i have make sure the build configurations x86 windows mingw debug, same with glus. Here are the errors that i get.

> Description	Resource	Path	Location	Type
C:\Users\publicENEMY\Source\Repos\OpenGLMcNopper\External\x86\Windows\MinGW\lib/libglfw3.a(wgl_context.c.obj): bad reloc address 0x20 in section `.eh_frame'	Example01		 	C/C++ Problem
final link failed: Invalid operation	Example01		 	C/C++ Problem
make: *** [../../Binaries/Example01_DBG.exe] Error 1	Example01		 	C/C++ Problem
more undefined references to `_wassert' follow	Example01		line 0, external location: C:\Users\publicENEMY\Source\Repos\OpenGLMcNopper\External\x86\Windows\MinGW\lib\libglfw3.a(wgl_context.c.obj):wgl_context.c	C/C++ Problem
undefined reference to `__ms_vsnprintf'	Example01		line 0, external location: C:\Users\publicENEMY\Source\Repos\OpenGLMcNopper\External\x86\Windows\MinGW\lib\libglfw3.a(init.c.obj):init.c	C/C++ Problem
undefined reference to `_wassert'	Example01		line 0, external location: C:\Users\publicENEMY\Source\Repos\OpenGLMcNopper\External\x86\Windows\MinGW\lib\libglfw3.a(wgl_context.c.obj):wgl_context.c	C/C++ Problem

How do i solve this?

**Comment by McNopper** [comment]
I am using this MinGW toolchain:
http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/5.1.0/threads-posix/dwarf/
As stated in the README, if you get build errors, please rebuild the external libraries.

**Comment by publicENEMY** [comment]
so what should i do? uninstall my mingw and install mingw from your link? or should i rebuild external libraries? which external libraries? glfw?

**Comment by McNopper** [comment]
Beginning line 16 of the README.txt in the GLUS folder:
"If you get build errors:

- Please make sure, that you install all the needed header and libraries.
- Pre-build libraries are located in the External project folder. If you want, replace these libraries with your own build.
- Libraries for the Raspberry PI platform are not included.
- Libraries for the i.MX6 platform are not included.
- Libraries for OpenGL ES and OpenVG are not included."

I suggest that you either create CMake and/or Visual C++ project files for the examples and then you can use your prefered environment.

Or, please Google it, on how to use MinGW, Eclipse, building and linking libraries - especially from different compileres - and then it will an easy task to build the OpenGL examples.
Sorry, but I cannot support you on these basics.

**Comment by publicENEMY** [comment]
I just told you that your build instruction does not contain enough information to get it build. I follow your guide to the letter and failed. You gave new instruction and still failed. The way I see it im helping testing your instructions. 

Oh well. 

"Also, if the developers of a library can't be bothered to provide a decent build system, then their library isn't worth using. They clearly don't respect your time, so why should you bother using it?" Nicol Bolas

**Comment by McNopper** [comment]
I will improve the build instructions sooner or later.
