### ISSUE TITLE
Please add license to this repo

### ISSUE THREAD

**Issue by Kromster80** [McNopper/OpenGL#14]
It would be nice to clearly see under which license this repo is published.

**Comment by alexpanter** [comment]
Same! No license implicitly just means public, but for the incredible code samples provided the author(s?) does indeed deserve recognition. At the very least I will add a link to this repo in my projects! And thank you for making this code available!

**Comment by McNopper** [comment]
Maybe an Apache license for the examples would make sense? Please note, that GLUS is using a GNU LESSER GENERAL PUBLIC LICENSE.

**Comment by paultallard** [comment]
Perhaps it is a shortcoming of Githubs comment system but I cannot tell which repo you guys are referring to. There seems to be no reference back to the repo. Can you give me a clue?

**Comment by Kromster80** [comment]
@paultallard I hate to be Captain Obvious here, but we are commenting in the https://github.com/McNopper/OpenGL and the issue is about code in _this_ repo xD

**Comment by McNopper** [comment]
Fixed here: https://github.com/McNopper/OpenGL/commit/42fa2736e2b37db1df99c2b205279855ec6f2b1d
