### ISSUE TITLE
Support request: how can i make this run on an unusual nonstandard platform?

### ISSUE THREAD

**Issue by XanCraft21** [McNopper/OpenGL#26]
Hello, i was wondering if it is possible to make this library run on nonstandard platforms that usually can’t run these kinds of software. My platform has no GPU or integrated graphics, it cannot run shaders, no operating system, and it is very limited in hardware, the graphics can only run in software.

My platform of choice is a microcontroller, but a more powerful one. My software of choice is the Arduino IDE. The coding language is c++11, and it is rather outdated.

I am looking for software that can run 3D graphics on a small device, but it is kind of hard to find such software. I found a port of opengl called tinygl, and i got it working with very few small modifications. There is also another port that doesn’t work since it has no frame buffer, but rather an encoded GPU signal.

It may be impossible to make this library work on my platform, but i wanted to see if i can with some help. Thank you for any help you can give me.

**Comment by McNopper** [comment]
This library uses OpenGL 3 and 4, so in your case, you would need to have a software rasterizer supporting OpenGL 3 and 4. I did have a quick look at TinyGL and it only support GL version 1.1. Also, it states to be not GL compliant.
Also did have a look at the Arduino IDE forum and did find this project: https://github.com/EmberGL-org/EmberGL
However, alos not fully compliant.

What will probably work is to cherry pick code snipets from my library and just try out things for your use case.
However, as most examples are based on shaders, many code snippets will probably not work.

**Comment by XanCraft21** [comment]
Thank you, i will take a look into the other library you linked. In the future i will try the cherry pick code snippets thing, even though it may not work.
